"""Intake question/answer models — the Triage agent's adaptive clarifying interview (P2-02)."""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import CheckConstraint, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.db.types import GUID
from app.models.base import Base, CreatedAtMixin, UUIDPrimaryKeyMixin

_QUESTION_TYPES = ("red_flag", "relevant_negative", "clarifying", "history", "exam")


class IntakeQuestion(UUIDPrimaryKeyMixin, CreatedAtMixin, Base):
    """A single highest-information-gain clarifying question generated by the Triage agent."""

    __tablename__ = "intake_questions"
    __table_args__ = (
        CheckConstraint(
            f"question_type IN ({', '.join(repr(t) for t in _QUESTION_TYPES)})",
            name="ck_intake_questions_type",
        ),
    )

    session_id: Mapped[uuid.UUID] = mapped_column(
        GUID(), ForeignKey("reasoning_sessions.id"), nullable=False, index=True
    )
    question_text: Mapped[str] = mapped_column(Text, nullable=False)
    question_type: Mapped[str] = mapped_column(String(30), nullable=False, default="clarifying")
    rationale: Mapped[str | None] = mapped_column(Text, nullable=True)
    sequence_order: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    info_gain_score: Mapped[float | None] = mapped_column(nullable=True)
    answered_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)


class IntakeAnswer(UUIDPrimaryKeyMixin, CreatedAtMixin, Base):
    """Clinician's response to an IntakeQuestion."""

    __tablename__ = "intake_answers"

    question_id: Mapped[uuid.UUID] = mapped_column(
        GUID(), ForeignKey("intake_questions.id"), nullable=False, index=True
    )
    session_id: Mapped[uuid.UUID] = mapped_column(
        GUID(), ForeignKey("reasoning_sessions.id"), nullable=False, index=True
    )
    answer_text: Mapped[str] = mapped_column(Text, nullable=False)
